version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    args:
      VITE_SECRET_TOKEN: ${REACT_APP_API_URL}
    ports:
      - '3500:3000'
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm start
