version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_SECRET_TOKEN: ${REACT_APP_API_URL}  # Передаем аргумент сборки
    ports:
      - '3500:3000'  # Убедитесь, что порт 3500 не занят
    environment:
      - NODE_ENV=production
      - VITE_SECRET_TOKEN=${REACT_APP_API_URL}  # Устанавливаем переменные окружения
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm start
