name: Build and Deploy

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted 

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker-compose build --build-arg VITE_SECRET_TOKEN=${{ secrets.REACT_APP_API_URL }}

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: SSH to server and deploy
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 33 
          script: |
            cd /home/hataie/moviesage
            docker-compose pull  # Обновляем образы
            docker-compose stop || true
            docker-compose rm -f || true
            docker-compose up -d  # Запускаем контейнеры в фоновом режиме
