name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted 

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Check secrets
        run: 
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}"
          echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}"
          
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: List Docker images
        run: docker images
        
      - name: List Docker containers
        run: docker ps -a
      - name: Build and Push Docker image
        run: |
          docker build -t hataie/movie_sage_frontend:latest .
          docker push hataie/movie_sage_frontend:latest

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: SSH to server and deploy
        uses: appleboy/ssh-action@v0.1.4
        with:

          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 33 
          script: |
            docker pull hataie/movie_sage_frontend:latest
            docker stop movie_sage_frontend || true
            docker rm movie_sage_frontend || true
            docker run -d --name movie_sage_frontend -p 80:80 hataie/movie_sage_frontend:latest
