name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted 

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          docker build -t your_dockerhub_username/your_image_name:latest .
          docker push your_dockerhub_username/your_image_name:latest

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: SSH to server and deploy
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            docker pull your_dockerhub_username/your_image_name:latest
            docker stop your_container_name || true
            docker rm your_container_name || true
            docker run -d --name your_container_name -p 80:80 your_dockerhub_username/your_image_name:latest
